name: Update branch

on:
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: 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
          script: |
            // Get all open MRs

            const pullsResponse = await github.rest.pulls.list({
              ...context.repo,
              base: "main"
              // state: "open"
            });
            
            const prs = pullsResponse.data

            // update all MRs with main.
            await Promise.all(
              prs.map((pr) => {
                  github.rest.pulls.updateBranch({
                      ...context.repo,
                      pull_number: pr.number,
                  })
              }),
            )