name: Update branch

on:
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // Get a list of all issues created by the PR opener
            // See: https://octokit.github.io/rest.js/#pagination
            const baseBranch = github.context.payload.ref
            const pullsResponse = await client.pulls.list({
              ...github.context.repo,
              base: baseBranch,
              state: 'open',
            })
            
            const prs = pullsResponse.data


            await Promise.all(
              prs.map((pr) => {
                  client.pulls.updateBranch({
                      ...github.context.repo,
                      pull_number: pr.number,
                  })
              }),
            )