name: Update branch

on:
  workflow_call:
    inputs:
      branch:
        description: 'Name of the branch to update with, defaults to main'
        required: false
        default: 'main'
        type: 'string'

jobs:
  welcome:
    name: Updates Open PR Branches with base branch
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TESTBEST }}
          script: |
            // Get all open MRs
            const pullsResponse = await github.rest.pulls.list({
              ...context.repo,
              base: "${{ inputs.branch }}",
              state: "open"
            });
            const prs = pullsResponse.data

            // update all MRs with main.
            await Promise.allSettled(
              prs.map((pr) => {
                  github.rest.pulls.updateBranch({
                      ...context.repo,
                      pull_number: pr.number,
                  })
              }),
            )
