name: Update branch

on:
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TESTBEST }}
          script: |
            // Get all open MRs
            // My comment

            const pullsResponse = await github.rest.pulls.list({
              ...context.repo,
              base: "main",
              state: "open"
            });
            
            const prs = pullsResponse.data
            const test = "hello"

            // update all MRs with main.
            await Promise.all(
              prs.map((pr) => {
                  github.rest.pulls.updateBranch({
                      ...context.repo,
                      pull_number: pr.number,
                  })
              }),
            )